ALTER TABLE media ADD COLUMN IF NOT EXISTS owner_type ENUM('SELLER', 'SUPERADMIN') NOT NULL DEFAULT 'SELLER' AFTER alt_text;
ALTER TABLE media ADD COLUMN IF NOT EXISTS owner_id BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER owner_type;
ALTER TABLE media ADD INDEX IF NOT EXISTS idx_media_owner (owner_type, owner_id);
