ALTER TABLE media ADD COLUMN IF NOT EXISTS width SMALLINT UNSIGNED NOT NULL DEFAULT 1 AFTER byte_size;
ALTER TABLE media ADD COLUMN IF NOT EXISTS height SMALLINT UNSIGNED NOT NULL DEFAULT 1 AFTER width;
ALTER TABLE media ADD COLUMN IF NOT EXISTS used_at DATETIME NULL AFTER owner_id;
